spring:
  datasource:
    url: jdbc:mysql://172.28.1.58:3306/act-test?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: dayi
    password: monda123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 1000
      pool-name: HikariPool

