spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
    schema: classpath:/db/schema-h2.sql
    data: classpath:/db/data-h2.sql
    #connection-test-query: SELECT 1
    #test-while-idle: true
    #test-on-borrow: true
    #validation-interval: 10000
    #log-validation-errors: true
    #validation-query: SELECT 1

h2:
    console:
      path: /h2
      enabled: true

