spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
    schema: classpath:/db/schema-h2.sql
    data: classpath:/db/data-h2.sql

h2:
    console:
      path: /h2
      enabled: true

